---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 22003.
--- DateTime: 2024-06-25 15:47
---

local key = KEYS[1]
local cntKey = key..":cnt"
local expectedCode = ARGV[1]

local cnt = tonumber(redis.call("get", cntKey))
local code = redis.call("get", key)

if cnt == nil or cnt <= 0 then
    return -1
end

if code == expectedCode then
    redis.call("set", cntKey, 0)
    return 0
else
    redis.call("decr", cntKey)
    return -2
end 