apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-claim-v1
spec:
  storageClassName: manual-v1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

  